config/routes.rb
Rails.application.routes.draw do

  root to: 'blogs#index'

  resources:blogs do
    collection do
      post :confirm
    end
  end

  def new
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence:true
  validates :content, presence: true, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :get_blog, only:[:show,:edit,:update,:destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
        @blog = Blog.new(blog_params)
      else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to new_blog_path, notice: "ブログを作成しました"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice:"ブログの編集をしました"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:'ブログの削除に成功しました'
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title,:content)
  end

  def get_blog
    @blog = Blog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def select_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%=form_with(model: @blog, local:true, url: select_new_or_edit ) do |form| %>

  <% if @blog.errors.any? %>
    <div id="error_expalanation">
      <h2><%= @blog.errors.count %>件のエラーがあります</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class=blog_title"">
    <%=form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class=blog_title"">
    <%=form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to'ブログ一覧画面を確認する',blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する?</h3>

<%= form_with(model: @blog, url:blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>RailsTask_blogApp</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Blog一覧</h1>
<div><%= notice %></div>
<table>
  <tr>
    <th>ブログタイトル</th>
    <th>内容</th>
  </tr>

  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%=link_to '詳細を確認する', blog_path(blog.id) %></td>
    <td><%= link_to'ブログを編集する', edit_blog_path(blog.id), data: { confirm: '編集しますか？'} %></td>
    <td><%= link_to'ブログを削除する', blog_path(blog.id),method: :delete, data:{confirm: '本当に削除しますか？'} %></td>
  </tr>
  <% end %>

</table>

<%= link_to'ブログ作成画面にもどる',new_blog_path %>

app/views/blogs/new.html.erb
<h1>RailsTask_blogApp</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>

<p>ブログタイトル:<%= @blog.title %></p>
<p>内容:<%= @blog.content %></p>

<%=link_to 'ブログ一覧画面にもどる',blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>